<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <ProjectReference Include="..\IBTM.Core\IBTM.Core.csproj" />
    <ProjectReference Include="..\IBTM.Device\IBTM.Device.csproj" />
    <ProjectReference Include="..\IBTM.NgConveyor\IBTM.NgConveyor.csproj" />
  </ItemGroup>

</Project>
