<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Virtual'">
    <OutputPath>bin\Virtual\</OutputPath>
    <DefineConstants>$(DefineConstants);VIRTUAL_DEVELOPMENT</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IBTM.Virtual.Tests" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hardware\IBTM.Ajin\IBTM.Ajin.csproj" />
    <ProjectReference Include="..\Hardware\IBTM.AlphaMotion\IBTM.AlphaMotion.csproj" />
    <ProjectReference Include="..\Stations\IBTM.BoltFastening\IBTM.BoltFastening.csproj" />
    <ProjectReference Include="..\Stations\IBTM.BoltFeeder\IBTM.BoltFeeder.csproj" />
    <ProjectReference Include="..\Stations\IBTM.Conveyor\IBTM.Conveyor.csproj" />
    <ProjectReference Include="..\Shared\IBTM.Core\IBTM.Core.csproj" />
    <ProjectReference Include="..\Shared\IBTM.Device\IBTM.Device.csproj" />
    <ProjectReference Include="..\Hardware\IBTM.Hantas\IBTM.Hantas.csproj" />
    <ProjectReference Include="..\Hardware\IBTM.Hik\IBTM.Hik.csproj" />
    <ProjectReference Include="..\Stations\IBTM.Inspection\IBTM.Inspection.csproj" />
    <ProjectReference Include="..\Stations\IBTM.Inspection.Training\IBTM.Inspection.Training.csproj" />
    <ProjectReference Include="..\Stations\IBTM.NgConveyor\IBTM.NgConveyor.csproj" />
    <ProjectReference Include="..\Stations\IBTM.PcbBuffer\IBTM.PcbBuffer.csproj" />
    <ProjectReference Include="..\Stations\IBTM.PcbPlacement\IBTM.PcbPlacement.csproj" />
    <ProjectReference Include="..\Stations\IBTM.PcbSupply\IBTM.PcbSupply.csproj" />
    <ProjectReference Include="..\Shared\IBTM.Storage\IBTM.Storage.csproj" />
    <ProjectReference Include="..\Hardware\IBTM.Virtual\IBTM.Virtual.csproj" />
  </ItemGroup>

</Project>
