<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBTM.Device\IBTM.Device.csproj" />
    <ProjectReference Include="..\IBTM.Inspection\IBTM.Inspection.csproj" />
  </ItemGroup>

</Project>
