<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
    <PackageReference Include="TorchSharp-cpu" Version="0.106.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBTM.Core\IBTM.Core.csproj" />
    <ProjectReference Include="..\IBTM.Inspection\IBTM.Inspection.csproj" />
  </ItemGroup>

</Project>
