// <auto-generated />
using IBTM.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBTM.Storage.Migrations
{
    [DbContext(typeof(MachineDb))]
    [Migration("20260907084615_InitialMachine")]
    partial class InitialMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("IBTM.Storage.RecipeImageRow", b =>
                {
                    b.Property<string>("RecipeName")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RecipeName", "Number");

                    b.ToTable("RecipeImages");
                });

            modelBuilder.Entity("IBTM.Storage.RecipeRow", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("IBTM.Storage.SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("IBTM.Storage.RecipeImageRow", b =>
                {
                    b.HasOne("IBTM.Storage.RecipeRow", null)
                        .WithMany()
                        .HasForeignKey("RecipeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
