<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Basler.Pylon">
      <HintPath>Basler\Basler.Pylon.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
