<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBTM.Core\IBTM.Core.csproj" />
    <ProjectReference Include="..\IBTM.Device\IBTM.Device.csproj" />
    <ProjectReference Include="..\IBTM.Stations.BoltFastening\IBTM.Stations.BoltFastening.csproj" />
    <ProjectReference Include="..\IBTM.Stations.Inspection\IBTM.Stations.Inspection.csproj" />
    <ProjectReference Include="..\IBTM.Stations.PcbPlacement\IBTM.Stations.PcbPlacement.csproj" />
  </ItemGroup>

</Project>
