<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\IBTM.Core\IBTM.Core.csproj" />
    <ProjectReference Include="..\..\Shared\IBTM.Device\IBTM.Device.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="AXL.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="AXL.lib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="EzBasicAxl.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
